# Generated by Django 2.2.16 on 2022-08-23 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20220823_1704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ('author',)},
        ),
    ]
